#!/usr/bin/env bash

SCRIPT_PATH=${0%/*}
cd "$SCRIPT_PATH"

echo ">> Init/update git submodule(s)"
git submodule init
git submodule update

echo ">> Export dotfiles"
for i in export/*;do
    abspath="$SCRIPT_PATH/$i"
    target="$HOME/.${i##*/}"

    if [ -e "$target" ] || [ -L "$target" ];then
        echo "Moving $target to /tmp/"
        mv "$target" /tmp/
    fi

    echo "$abspath -> $target"
    ln -s "$abspath" "$target"
done

cd - > /dev/null
